export const FONT = {
  Black: 'SFProDisplay-Black',
  BlackItalic: 'SFProDisplay-BlackItalic',
  Bold: 'SFProDisplay-Bold',
  BoldItalic: 'SFProDisplay-BoldItalic',
  Heavy: 'SFProDisplay-Heavy',
  HeavyItalic: 'SFProDisplay-HeavyItalic',
  Light: 'SFProDisplay-Light',
  LightItalic: 'SFProDisplay-LightItalic',
  Medium: 'SFProDisplay-Medium',
  MediumItalic: 'SFProDisplay-MediumItalic',
  Regular: 'SFProDisplay-Regular',
  RegularItalic: 'SFProDisplay-RegularItalic',
  SemiBold: 'SFProDisplay-SemiBold',
  SemiBoldItalic: 'SFProDisplay-SemiBoldItalic',
  Thin: 'SFProDisplay-Thin',
  ThinItalic: 'SFProDisplay-ThinItalic',
  Ultralight: 'SFProDisplay-Ultralight',
  UltralightItalic: 'SFProDisplay-UltralightItalic',
};
